#!/usr/bin/env python3
"""
Generate L10n/en.commodities.template from EDCD FDevIDs commodity.csv.

Each row maps a stable journal/API commodity key to the official in-game English name:
  "commodity:aluminium" = "Aluminium";

Regenerate when FDevIDs updates:
  python scripts/generate_commodity_l10n_template.py

Merged into locale *.strings by scripts/generate_plugin_l10n.py (or refresh_changed_l10n.py).
"""

from __future__ import annotations

import csv
import urllib.request
from pathlib import Path

FDEV_URL = "https://raw.githubusercontent.com/EDCD/FDevIDs/master/commodity.csv"
OUT = Path(__file__).resolve().parents[1] / "L10n" / "en.commodities.template"

HEADER = """/* Ravencolonial EDMC — colonization overlay commodity display names.
   Keys are commodity:{symbol_lower} matching normalize_commodity_key() / FDevIDs symbol.
   Auto-generated by scripts/generate_commodity_l10n_template.py — do not hand-edit rows. */

"""


def escape_strings(s: str) -> str:
    return s.replace('"', r"\"")


def main() -> int:
    with urllib.request.urlopen(FDEV_URL, timeout=60) as resp:  # nosec B310
        text = resp.read().decode("utf-8")

    rows: list[tuple[str, str]] = []
    for row in csv.DictReader(text.splitlines()):
        sym = (row.get("symbol") or "").strip()
        name = (row.get("name") or "").strip()
        cat = (row.get("category") or "").strip()
        if not sym or not name or cat == "NonMarketable":
            continue
        key = f"commodity:{sym.lower()}"
        rows.append((key, name))

    rows.sort(key=lambda kv: kv[0])
    lines = [HEADER.rstrip(), ""]
    for key, name in rows:
        lines.append(f'"{escape_strings(key)}" = "{escape_strings(name)}";')
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} commodity entries to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
